// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ErrorCode is the stable Work error vocabulary. Dependency-specific detail
 * stays at the Adapter boundary and is never used as a UI control protocol.
 */
export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorInvalidTransition = "INVALID_LIFECYCLE_TRANSITION",
    ErrorPlatformUnsupported = "PLATFORM_UNSUPPORTED",
    ErrorDSHRuntimeNotFound = "DSH_RUNTIME_NOT_FOUND",
    ErrorDSHVersionCheckFailed = "DSH_VERSION_CHECK_FAILED",
    ErrorDSHUnsupportedVersion = "DSH_UNSUPPORTED_VERSION",
    ErrorDSHStartFailed = "DSH_START_FAILED",
    ErrorDSHEarlyExit = "DSH_EARLY_EXIT",
    ErrorDSHReadinessTimeout = "DSH_READINESS_TIMEOUT",
    ErrorDSHInvalidReadiness = "DSH_INVALID_READINESS",
    ErrorProcessStartFailed = "PROCESS_START_FAILED",
    ErrorProcessCleanupFailed = "PROCESS_CLEANUP_FAILED",
    ErrorProcessStopFailed = "PROCESS_STOP_FAILED",
    ErrorCancelled = "CANCELLED",
};

/**
 * Failure is safe to project to the trusted UI. Detail is bounded diagnostic
 * context and must already be redacted by the producing Adapter.
 */
export interface Failure {
    "code": ErrorCode;
    "summary": string;
    "retryable": boolean;
    "effectOccurred": boolean;
    "correlationId": string;
    "detail"?: string;
}

/**
 * Phase identifies the bounded startup or shutdown step currently in progress.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhaseIdle = "idle",
    PhaseConfiguration = "configuration",
    PhaseRuntime = "runtime",
    PhaseWorker = "worker",
    PhaseReadiness = "readiness",
    PhaseWorkspace = "workspace",
    PhaseStopping = "stopping",
    PhaseFailed = "failed",
};

/**
 * State is the platform-neutral lifecycle state projected to the trusted UI.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateStarting = "Starting",
    StateReady = "Ready",
    StateStopping = "Stopping",
    StateStopped = "Stopped",
    StateFailed = "Failed",
};

/**
 * Status is the immutable read model consumed by the frontend.
 */
export interface Status {
    "state": State;
    "phase": Phase;
    "generationId"?: string;
    "workspaceUrl"?: string;
    "error"?: Failure | null;
    "canRetry": boolean;
    "canCancel": boolean;
    "correlationId"?: string;
}
