// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ArtifactIdentity {
    "kind": ArtifactKind;
    "name": string;
    "version"?: string;
    "platform"?: string;
    "architecture"?: string;
    "filename"?: string;
}

export enum ArtifactKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ArtifactNode = "node",
    ArtifactDSH = "dsh",
    ArtifactPlugin = "plugin",
};

export enum FailureKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FailureReachability = "reachability",
    FailureNotFound = "not-found",
    FailureAuthentication = "authentication",
    FailureAuthorization = "authorization",
    FailureIntegrity = "integrity",
    FailureSemantic = "semantic",
    FailureCanceled = "canceled",
    FailureLocalIO = "local-io",
};

export interface OperationFailure {
    "kind": FailureKind;
    "summary": string;
    "retryable": boolean;
}

export interface OperationResult {
    "succeeded": boolean;
    "route"?: Route;
    "failure"?: OperationFailure | null;
}

export enum OperationState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationActive = "active",
    OperationSucceeded = "succeeded",
    OperationFailed = "failed",
    OperationCanceled = "canceled",
};

/**
 * OperationStatus is the bounded, credential-free projection emitted to the
 * trusted Settings surface for one explicit artifact operation.
 */
export interface OperationStatus {
    "operationId": string;
    "artifact": ArtifactIdentity;
    "state": OperationState;
    "step": string;
    "route"?: Route;
    "attempt"?: number;
    "receivedBytes"?: number;
    "totalBytes"?: number;
    "hasTotal": boolean;
    "canCancel": boolean;
    "result"?: OperationResult | null;
}

export enum Route {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RouteOfficial = "official",
    RouteMirror = "mirror",
    RouteLocal = "local",
};
