// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lifecycle$0 from "../lifecycle/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspacecontext$0 from "../workspacecontext/models.js";

export function Cancel(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(1612573212);
}

export function DisableFaultPlugin(packageName: string): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(598114413, packageName);
}

export function GetLocale(): $CancellablePromise<settings$0.Locale> {
    return $Call.ByID(3068536916);
}

export function GetStartupOutput(): $CancellablePromise<app$0.StartupOutput> {
    return $Call.ByID(996208986);
}

export function GetStatus(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3795814092);
}

export function GetTheme(): $CancellablePromise<dshmanager$0.ThemePreference> {
    return $Call.ByID(3636700019);
}

export function GetWorkspaceStatus(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(210882421);
}

export function OpenRuntimeSettings(): $CancellablePromise<void> {
    return $Call.ByID(2685934971);
}

export function Quit(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(4034652397);
}

export function RemoveFaultPlugin(packageName: string): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3791506921, packageName);
}

export function Restart(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3758916889);
}

export function Start(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(1458355814);
}

export function StartWithWorkspace(request: workspacecontext$0.Request): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(666163587, request);
}
