// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";

export function BackupProfile(request: dshmanager$0.ProfileBackupRequest): $CancellablePromise<dshmanager$0.ProfileBackupResult> {
    return $Call.ByID(1114712960, request);
}

export function CancelAcquisition(): $CancellablePromise<void> {
    return $Call.ByID(4177881910);
}

export function CancelRestore(): $CancellablePromise<void> {
    return $Call.ByID(439630555);
}

export function CancelRuntime(): $CancellablePromise<void> {
    return $Call.ByID(2975873261);
}

export function CloneProfile(request: dshmanager$0.ProfileCloneRequest): $CancellablePromise<dshmanager$0.ProfileCloneResult> {
    return $Call.ByID(545840751, request);
}

export function DeleteProfile(request: dshmanager$0.ProfileDeleteRequest): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1722376087, request);
}

export function DeleteProfileBackup(ref: dshmanager$0.ProfileRef, fileName: string): $CancellablePromise<void> {
    return $Call.ByID(2120910925, ref, fileName);
}

export function DeleteRestorePoint(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1854083254, id);
}

export function EnterSafeMode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3176544163);
}

export function ExitSafeMode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(952449787);
}

export function ExportProfile(ref: dshmanager$0.ProfileRef): $CancellablePromise<string> {
    return $Call.ByID(2628283212, ref);
}

export function GetSnapshot(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(596675583);
}

export function GetTheme(): $CancellablePromise<dshmanager$0.ThemePreference> {
    return $Call.ByID(761292424);
}

export function ImportProfileBackup(): $CancellablePromise<dshmanager$0.ProfileCloneResult | null> {
    return $Call.ByID(2600781331);
}

export function InstallLatestNode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(264853003);
}

export function InstallPlugin(request: dshmanager$0.PluginInstallRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(18327971, request);
}

export function InstallRuntime(version: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(778756996, version);
}

export function ListLoaderEntries(request: dshmanager$0.LoaderEntryListRequest): $CancellablePromise<dshmanager$0.LoaderLayer[] | null> {
    return $Call.ByID(4173035054, request);
}

export function ListPlugins(request: dshmanager$0.PluginListRequest): $CancellablePromise<dshmanager$0.PluginInfo[] | null> {
    return $Call.ByID(2803065503, request);
}

export function ListProfileBackups(ref: dshmanager$0.ProfileRef): $CancellablePromise<dshmanager$0.ProfileBackupResult[] | null> {
    return $Call.ByID(59962581, ref);
}

export function OpenProfileBackups(ref: dshmanager$0.ProfileRef): $CancellablePromise<void> {
    return $Call.ByID(1028442493, ref);
}

export function PreviewRestorePoint(id: string): $CancellablePromise<dshmanager$0.RestorePoint> {
    return $Call.ByID(4108000551, id);
}

export function RefreshDSHReleases(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2415585129);
}

export function RefreshLatestNode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2720604175);
}

export function RegisterDataDirectory(dataDirectory: dshmanager$0.DataDirectoryInfo): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3320420443, dataDirectory);
}

export function RegisterRuntime(runtime: dshmanager$0.RuntimeInfo): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3786902276, runtime);
}

export function RemoveDataDirectory(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2363203152, id);
}

export function RemoveNode(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(473909717, id);
}

export function RemovePlugin(request: dshmanager$0.PluginRemoveRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(1339556818, request);
}

export function RemoveRuntime(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3588728851, id);
}

export function RenameProfile(request: dshmanager$0.ProfileRenameRequest): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1510892236, request);
}

export function RenameRestorePoint(id: string, label: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2252798939, id, label);
}

export function ResolveLaunch(request: dshmanager$0.LaunchRequest): $CancellablePromise<dshmanager$0.ResolvedLaunch> {
    return $Call.ByID(2564747644, request);
}

export function RestoreKnownGood(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3334924869);
}

export function RestorePoint(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3932578109, id);
}

export function RestoreProfileBackup(request: dshmanager$0.ProfileRestoreRequest): $CancellablePromise<dshmanager$0.ProfileCloneResult> {
    return $Call.ByID(1225697940, request);
}

export function RetryLastSwitch(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2560451769);
}

export function SaveRestorePoint(label: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1651157004, label);
}

export function SetLoaderEntryDisabled(request: dshmanager$0.LoaderEntryDisableRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(3732322700, request);
}

export function SetPluginDisabled(request: dshmanager$0.PluginDisableRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(4269219424, request);
}

export function SetRunContext(target: dshmanager$0.RunContext): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3418084503, target);
}

export function UpgradePlugin(request: dshmanager$0.PluginUpgradeRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(2877447132, request);
}
