// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuiltinComponentStatus is the read-only load state of an application-owned DSH Client.
 */
export interface BuiltinComponentStatus {
    "id": string;
    "state": string;
}

/**
 * ShellPet is what the shell menu needs from the pet panel.
 */
export interface ShellPet {
    "ready": boolean;
    "visible": boolean;
}
