// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellPet is what the shell menu needs from the pet panel.
 */
export interface ShellPet {
    "ready": boolean;
    "visible": boolean;
}
