// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "../pet/models.js";

export function ClearPetSelection(): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(2637190594);
}

export function GetPetOverlay(): $CancellablePromise<app$0.PetOverlayState> {
    return $Call.ByID(1256431805);
}

export function GetPetPanel(): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(526961231);
}

export function GetPetPlayback(known: string): $CancellablePromise<pet$0.Playback | null> {
    return $Call.ByID(699526466, known);
}

export function GetPetPresentation(): $CancellablePromise<app$0.PetOverlayState> {
    return $Call.ByID(4125465215);
}

export function GetPetPreview(previewRef: string): $CancellablePromise<string> {
    return $Call.ByID(1484267361, previewRef);
}

export function OpenPetActivity(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1887853130, sessionID);
}

export function PetGesture(kind: string, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3304703058, kind, x, y);
}

export function PreviewPet(stableSourceKey: string): $CancellablePromise<app$0.PetPreview> {
    return $Call.ByID(2419778911, stableSourceKey);
}

export function RefreshPetCatalog(): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(3662283885);
}

export function SelectPet(stableSourceKey: string): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(1010110107, stableSourceKey);
}

export function SetPetAlwaysOnTop(enabled: boolean): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(3850115946, enabled);
}

export function SetPetHitRegions(regions: app$0.PetHitRegion[] | null): $CancellablePromise<void> {
    return $Call.ByID(1021263897, regions);
}

export function SetPetReducedMotion(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3494508025, enabled);
}

export function SetPetSize(percent: number): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(2372741978, percent);
}

export function SetPetVisibility(visible: boolean): $CancellablePromise<app$0.PetPanel> {
    return $Call.ByID(3666211775, visible);
}
