// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

export function GetSettings(): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(100181646);
}

export function SetAutomaticRuntimeRollback(enabled: boolean): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(1677788962, enabled);
}

export function SetLocale(locale: string): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(4070290345, locale);
}

export function SetNotificationPreference(key: string, enabled: boolean): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(2103107557, key, enabled);
}
