// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellService serves the trusted workbench shell from the UI process, which
 * owns the windows; it never reaches the background.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenSettings shows dsh-work Settings at a section the shell menu offers.
 */
export function OpenSettings(section: string): $CancellablePromise<void> {
    return $Call.ByID(671240417, section);
}
