// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellService serves the trusted workbench shell from the UI process, which
 * owns the windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginBuiltinComponents marks each built-in Client as loading for the current DSH frame.
 */
export function BeginBuiltinComponents(): $CancellablePromise<void> {
    return $Call.ByID(1175616448);
}

/**
 * GetBuiltinComponents returns a detached status snapshot to the workspace or Settings window.
 */
export function GetBuiltinComponents(): $CancellablePromise<$models.BuiltinComponentStatus[] | null> {
    return $Call.ByID(65460131);
}

/**
 * GetPet reports whether a pet is selected and visible.
 */
export function GetPet(): $CancellablePromise<$models.ShellPet> {
    return $Call.ByID(2012532601);
}

/**
 * OpenSettings shows dsh-work Settings at a section the shell menu offers.
 */
export function OpenSettings(section: string): $CancellablePromise<void> {
    return $Call.ByID(671240417, section);
}

/**
 * ReportBuiltinComponent accepts a readiness handshake from the framed DSH Client.
 */
export function ReportBuiltinComponent(id: string): $CancellablePromise<void> {
    return $Call.ByID(1278708676, id);
}

/**
 * ResetBuiltinComponents marks the DSH Clients inactive when the frame is removed.
 */
export function ResetBuiltinComponents(): $CancellablePromise<void> {
    return $Call.ByID(2063574054);
}

/**
 * SaveZoom remembers the workbench zoom factor for the next start.
 */
export function SaveZoom(zoom: number): $CancellablePromise<void> {
    return $Call.ByID(447002478, zoom);
}

/**
 * SetPetVisible shows or hides the selected pet.
 */
export function SetPetVisible(visible: boolean): $CancellablePromise<$models.ShellPet> {
    return $Call.ByID(3239166025, visible);
}
