// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storagepaths$0 from "../storagepaths/models.js";

export function CancelMigration(): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(719167495);
}

export function ChooseDirectory(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(4285211073, currentPath);
}

export function DefaultUserDataPath(root: string): $CancellablePromise<string> {
    return $Call.ByID(2224926716, root);
}

export function GetLocations(): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(3058389291);
}

export function OpenLocation(userData: boolean): $CancellablePromise<void> {
    return $Call.ByID(54106492, userData);
}

export function SaveLocations(locations: storagepaths$0.Locations): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(4027120566, locations);
}
