// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostService is the intentionally narrow Wails binding surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lifecycle$0 from "../lifecycle/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspacecontext$0 from "../workspacecontext/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3418678552);
}

/**
 * GetLocale reads the dsh-work-owned language preference for the trusted startup
 * surface. It is read-only here; SettingsService remains the write boundary.
 */
export function GetLocale(): $CancellablePromise<settings$0.Locale> {
    return $Call.ByID(1021097304);
}

/**
 * GetStartupOutput returns the bounded, redacted stdout/stderr tails for the
 * active or last startup attempt so the user can inspect and copy them.
 */
export function GetStartupOutput(): $CancellablePromise<$models.StartupOutput> {
    return $Call.ByID(2399609318);
}

export function GetStatus(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3810866152);
}

/**
 * GetTheme projects the selected DSH data directory's appearance preference. DSH owns
 * the value; dsh-work only uses it to paint its trusted startup surface.
 */
export function GetTheme(): $CancellablePromise<dshmanager$0.ThemePreference> {
    return $Call.ByID(1276069119);
}

/**
 * GetWorkspaceStatus projects the current per-generation Workspace context to
 * the trusted Settings window. It is read-only and does not expose Host
 * controls from that surface.
 */
export function GetWorkspaceStatus(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(2318209329);
}

/**
 * OpenRuntimeSettings is the first-use recovery action for a missing local
 * runtime. It opens the trusted runtime-management surface but never starts an
 * acquisition itself.
 */
export function OpenRuntimeSettings(): $CancellablePromise<void> {
    return $Call.ByID(933763759);
}

export function Quit(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(4265271809);
}

export function Restart(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(39976093);
}

export function Start(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3063548498);
}

/**
 * StartWithWorkspace is the explicit session action for a DSH Workspace
 * surface. The request is resolved for one Worker generation and is not
 * persisted with the global Run context.
 */
export function StartWithWorkspace(request: workspacecontext$0.Request): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(2093500751, request);
}
