// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagerService is the trusted Settings-window binding for the nested DSH
 * manager. It exposes catalog, Run-context, runtime/data-directory and
 * profile-plugin operations; profile composition and plugin mutation still go
 * through DSH's public CLI seam, never direct file edits.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";

export function BackupProfile(request: dshmanager$0.ProfileBackupRequest): $CancellablePromise<dshmanager$0.ProfileBackupResult> {
    return $Call.ByID(784966172, request);
}

export function CancelAcquisition(): $CancellablePromise<void> {
    return $Call.ByID(2933888802);
}

export function CancelRestore(): $CancellablePromise<void> {
    return $Call.ByID(3248845655);
}

/**
 * CancelRuntime cancels the active explicit runtime pull from the trusted
 * Settings surface. Cancellation leaves no catalog entry; the installer owns
 * cleanup of its staging directory.
 */
export function CancelRuntime(): $CancellablePromise<void> {
    return $Call.ByID(656225601);
}

export function CloneProfile(request: dshmanager$0.ProfileCloneRequest): $CancellablePromise<dshmanager$0.ProfileCloneResult> {
    return $Call.ByID(3642858027, request);
}

export function DeleteProfile(request: dshmanager$0.ProfileDeleteRequest): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3806339691, request);
}

export function DeleteProfileBackup(ref: dshmanager$0.ProfileRef, fileName: string): $CancellablePromise<void> {
    return $Call.ByID(856008297, ref, fileName);
}

export function DeleteRestorePoint(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(816226698, id);
}

export function EnterSafeMode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(246338583);
}

export function ExitSafeMode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2298611703);
}

export function ExportProfile(ref: dshmanager$0.ProfileRef): $CancellablePromise<string> {
    return $Call.ByID(3399802680, ref);
}

export function GetSnapshot(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3706159683);
}

/**
 * GetTheme reads the selected DSH data directory's appearance preference. Settings uses
 * it while both trusted windows are open so its surface follows changes made
 * by DSH.
 */
export function GetTheme(): $CancellablePromise<dshmanager$0.ThemePreference> {
    return $Call.ByID(500405340);
}

export function ImportProfileBackup(): $CancellablePromise<dshmanager$0.ProfileCloneResult | null> {
    return $Call.ByID(4094017527);
}

export function InstallLatestNode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1383461839);
}

export function InstallPlugin(request: dshmanager$0.PluginInstallRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(1606435111, request);
}

export function InstallRuntime(version: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1408476440, version);
}

export function ListPlugins(request: dshmanager$0.PluginListRequest): $CancellablePromise<dshmanager$0.PluginInfo[] | null> {
    return $Call.ByID(3735864195, request);
}

export function ListProfileBackups(ref: dshmanager$0.ProfileRef): $CancellablePromise<dshmanager$0.ProfileBackupResult[] | null> {
    return $Call.ByID(968671673, ref);
}

export function OpenProfileBackups(ref: dshmanager$0.ProfileRef): $CancellablePromise<void> {
    return $Call.ByID(3482533913, ref);
}

export function PreviewRestorePoint(id: string): $CancellablePromise<dshmanager$0.RestorePoint> {
    return $Call.ByID(3894557475, id);
}

export function RefreshDSHReleases(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1946171845);
}

export function RefreshLatestNode(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(4253380379);
}

export function RegisterDataDirectory(dataDirectory: dshmanager$0.DataDirectoryInfo): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2482295343, dataDirectory);
}

export function RemoveDataDirectory(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3899737548, id);
}

export function RemoveNode(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2034113705, id);
}

export function RemovePlugin(request: dshmanager$0.PluginRemoveRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(4146020966, request);
}

export function RemoveRuntime(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1481344487, id);
}

export function RenameProfile(request: dshmanager$0.ProfileRenameRequest): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2984344992, request);
}

export function RenameRestorePoint(id: string, label: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(442631375, id, label);
}

export function ResolveLaunch(request: dshmanager$0.LaunchRequest): $CancellablePromise<dshmanager$0.ResolvedLaunch> {
    return $Call.ByID(1114420160, request);
}

export function RestoreKnownGood(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3365799665);
}

export function RestorePoint(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2272363761, id);
}

export function RestoreProfileBackup(request: dshmanager$0.ProfileRestoreRequest): $CancellablePromise<dshmanager$0.ProfileCloneResult> {
    return $Call.ByID(291893256, request);
}

export function RetryLastSwitch(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1457349837);
}

export function SaveRestorePoint(label: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3594135168, label);
}

export function SetRunContext(target: dshmanager$0.RunContext): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2077442307, target);
}

export function UpgradePlugin(request: dshmanager$0.PluginUpgradeRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(157594528, request);
}
