// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupOutput is the redacted DSH process output retained by the supervisor
 * while dsh-work is starting or recovering. It intentionally omits process
 * metadata and exposes no raw, unredacted stream.
 */
export interface StartupOutput {
    "stdout": string;
    "stderr": string;
}
