// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshactivity$0 from "../dshactivity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "../pet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

/**
 * PetOverlayState is the read-only projection consumed by the independent
 * overlay page. The frame is a Host-rendered data URL; it is never a source
 * path or a frontend-composed resource URL.
 */
export interface PetOverlayState {
    "runtime": pet$0.RuntimeState;
    "snapshot": pet$0.PetRuntimeSnapshot;
    "preview": PetPreview;
    "dataUrl"?: string;
    "activity": dshactivity$0.Snapshot;
}

/**
 * PetPanel is the safe Settings projection. PetCatalog already strips source
 * paths from its snapshot; the service adds current-selection and opaque
 * preview references without exposing a PetDefinition or package bytes.
 */
export interface PetPanel {
    "snapshot": pet$0.CatalogSnapshot;
    "preference": settings$0.PetPreference;
    "runtime": pet$0.RuntimeState;
    "sizePercent": number;
    "sizeAvailable": boolean;
}

/**
 * PetPreview is a safe, one-shot preview response. PreviewRef is an opaque,
 * short-lived Host handle; it is not a filesystem reference or resource URL.
 */
export interface PetPreview {
    "previewRef": string;
    "stableSourceKey": string;
    "displayName": string;
    "description"?: string;
    "assetId"?: string;
    "format"?: string;
    "width"?: number;
    "height"?: number;
}

/**
 * StartupOutput is the redacted DSH process output retained by the supervisor
 * while dsh-work is starting or recovering. It intentionally omits process
 * metadata and exposes no raw, unredacted stream.
 */
export interface StartupOutput {
    "stdout": string;
    "stderr": string;
}
