// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PetSettingsService is the trusted Settings-window boundary for Pet
 * discovery and preference changes. Browse operations never call
 * SetPetPreference. Selection is serialized here and commits only after the
 * catalog has revalidated the source and the renderer has passed preflight.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "../pet/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearPetSelection clears both the selected key and its visibility intent.
 */
export function ClearPetSelection(): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(921201294);
}

/**
 * GetPetOverlay returns the latest normalized runtime frame for the separate
 * Pet window. The overlay surface is read-only; state changes still enter
 * through the Host-owned lifecycle and Settings seams.
 */
export function GetPetOverlay(): $CancellablePromise<$models.PetOverlayState> {
    return $Call.ByID(370880673);
}

/**
 * GetPetPanel returns the current catalog snapshot, persisted preference and
 * derived runtime state without refreshing or persisting anything.
 */
export function GetPetPanel(): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(3162746507);
}

/**
 * GetPetPlayback fetches a selection's immutable media plan only when it changes.
 */
export function GetPetPlayback(known: string): $CancellablePromise<pet$0.Playback | null> {
    return $Call.ByID(3723972374, known);
}

/**
 * GetPetPresentation returns the timeline without encoding or transferring frames.
 */
export function GetPetPresentation(): $CancellablePromise<$models.PetOverlayState> {
    return $Call.ByID(1204963475);
}

/**
 * GetPetPreview resolves an opaque preview handle and renders only the
 * validated idle frame. The handle is the sole frontend capability: callers
 * cannot turn a stable key or package path into a resource URL themselves.
 */
export function GetPetPreview(previewRef: string): $CancellablePromise<string> {
    return $Call.ByID(3095908949, previewRef);
}

/**
 * OpenPetActivity returns to an existing DSH conversation from the pet surface.
 */
export function OpenPetActivity(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1561219750, sessionID);
}

/**
 * PetGesture accepts a fixed gesture vocabulary, never task or window commands.
 */
export function PetGesture(kind: string, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(728301918, kind, x, y);
}

/**
 * PreviewPet resolves the selected key through PetCatalog and returns only
 * bounded metadata plus an opaque Host-owned preview handle. It deliberately
 * does not change the persisted selection or visibility intent.
 */
export function PreviewPet(stableSourceKey: string): $CancellablePromise<$models.PetPreview> {
    return $Call.ByID(2049162339, stableSourceKey);
}

/**
 * RefreshPetCatalog refreshes discovery and returns the resulting safe panel.
 * A failed refresh may still return a stale panel because PetCatalog retains
 * the last usable snapshot; the refresh error remains visible to the caller.
 */
export function RefreshPetCatalog(): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(2584801697);
}

/**
 * SelectPet performs the explicit selection transaction. Resolve is the
 * commit-time source revalidation seam; renderer preflight and persistence
 * happen only after it succeeds. No failure mutates the old preference.
 */
export function SelectPet(stableSourceKey: string): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(1335756375, stableSourceKey);
}

/**
 * SetPetAlwaysOnTop applies and persists the Settings-owned window preference.
 */
export function SetPetAlwaysOnTop(enabled: boolean): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(1179487238, enabled);
}

/**
 * SetPetHitRegions reports normalized regions in the trusted pet viewport.
 */
export function SetPetHitRegions(regions: $models.PetHitRegion[] | null): $CancellablePromise<void> {
    return $Call.ByID(3364393621, regions);
}

/**
 * SetPetReducedMotion records the operating-system accessibility signal sent
 * by the app-owned overlay surface. It is not a package-controlled setting;
 * the Host applies it to the active Runtime and carries it across activation.
 */
export function SetPetReducedMotion(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(428254485, enabled);
}

/**
 * SetPetSize changes the persisted Pet dimensions through the Settings
 * surface. The slider is intentionally the only size control: native window
 * border resizing is disabled, while the Host-owned Resize hook applies the
 * same validated dimensions to the desktop overlay.
 */
export function SetPetSize(percent: number): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(741599062, percent);
}

/**
 * SetPetVisibility persists visibility intent, including while a pet is unavailable.
 */
export function SetPetVisibility(visible: boolean): $CancellablePromise<$models.PetPanel> {
    return $Call.ByID(302323867, visible);
}
