// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService exposes only the two desktop-owned location choices.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storagepaths$0 from "../storagepaths/models.js";

export function CancelMigration(): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(1595419003);
}

export function ChooseDirectory(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(1754624765, currentPath);
}

/**
 * DefaultUserDataPath keeps OS path semantics out of presentation code.
 */
export function DefaultUserDataPath(root: string): $CancellablePromise<string> {
    return $Call.ByID(3761392424, root);
}

export function GetLocations(): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(3921870951);
}

export function OpenLocation(userData: boolean): $CancellablePromise<void> {
    return $Call.ByID(1498417624, userData);
}

export function SaveLocations(locations: storagepaths$0.Locations): $CancellablePromise<storagepaths$0.State> {
    return $Call.ByID(2418005506, locations);
}
