// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Context is intentionally per-generation. It is never part of the durable
 * Work launch target or the global manager state.
 */
export interface Context {
    "generationId": string;
    "state": State;
    "id"?: string;
    "path"?: string;
    "title"?: string;
}

/**
 * Request is supplied by an explicit launch/session action. The DSH Workspace
 * surface is the source of the stable ID and canonical directory when it has
 * already resolved a Workspace.
 */
export interface Request {
    "id"?: string;
    "path"?: string;
    "title"?: string;
}

/**
 * State describes what the DSH Workspace surface must do for one session.
 * SelectionRequired is an explicit result, not a fallback to a process
 * directory or another Work-owned path.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateSelected = "selected",
    StateSelectionRequired = "selection-required",
};
