// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataDirectoryInfo is a DSH_HOME identity. Profiles and their plugin state
 * live under a data directory and are never properties of a runtime.
 */
export interface DataDirectoryInfo {
    "id": string;
    "name": string;
    "path": string;
    "ownership": DataDirectoryOwnership;
}

/**
 * DataDirectoryOwnership describes who owns the DSH data directory. A
 * dsh-work-owned directory is safe for dsh-work to create and maintain; a
 * user-owned directory is discovered only.
 */
export enum DataDirectoryOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DataDirectoryOwnershipDSHWork = "dsh-work",
    DataDirectoryOwnershipUser = "user",
};

/**
 * LaunchRequest is the validation input used by both GUI and CLI callers.
 */
export interface LaunchRequest {
    "runtimeId": string;
    "profile": ProfileRef;
}

export interface PluginInfo {
    "name": string;
    "version"?: string;
    "package": string;
    "spec"?: string;
    "installed": boolean;
}

export interface PluginInstallRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginListRequest {
    "target": PluginTarget;
}

export interface PluginRemoveRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginResult {
    "profile": ProfileRef;
    "plugins": PluginInfo[] | null;
    "restartRequired": boolean;
}

export interface PluginTarget {
    /**
     * Plugin state is scoped only by the DSH data directory and profile. The
     * manager resolves the current runtime at the mutation boundary.
     */
    "profile": ProfileRef;
}

/**
 * ProfileInfo is a read model. It does not compose or mutate DSH profiles;
 * those semantics remain behind the DSH public CLI seam.
 */
export interface ProfileInfo {
    "ref": ProfileRef;
    "path": string;
    "exists": boolean;
    "kind": ProfileKind;
    "launchable": boolean;
    "renamable": boolean;
    "autoInitialize": boolean;
    "pluginCount": number;
    "plugins"?: PluginInfo[] | null;
}

export enum ProfileKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileKindBuiltIn = "built-in",
    ProfileKindCustom = "custom",
};

/**
 * ProfileRef is intentionally two-dimensional. A profile name is not unique
 * across DSH data directories, so every selection and plugin operation must
 * carry both the data-directory identity and the profile name.
 */
export interface ProfileRef {
    "dataDirectoryId": string;
    "name": string;
}

/**
 * ProfileRenameRequest changes the directory-backed identity of a custom DSH
 * profile. Built-in profile names belong to the DSH adapter and are immutable.
 */
export interface ProfileRenameRequest {
    "profile": ProfileRef;
    "newName": string;
}

/**
 * ResolvedLaunch carries the validated catalog records alongside the
 * normalized target. Host uses this as one immutable handoff into the DSH
 * adapter, so it does not reconstruct data-directory/profile relationships
 * itself.
 */
export interface ResolvedLaunch {
    "target": RunContext;
    "runtime": RuntimeInfo;
    "dataDirectory": DataDirectoryInfo;
}

/**
 * RunContext is the complete dsh-work selection that defines one DSH Worker
 * generation. Runtime, DSH data directory and profile are one unit and cannot
 * be persisted or switched independently.
 */
export interface RunContext {
    "runtimeId": string;
    "profile": ProfileRef;
}

/**
 * RuntimeInfo is the platform-neutral read model for one immutable DSH
 * distribution. Path is the executable (or launcher) path, not a DSH data
 * directory.
 */
export interface RuntimeInfo {
    "id": string;
    "version": string;
    "path": string;
    "source": RuntimeSource;
    "installed": boolean;
    "removable": boolean;
}

/**
 * RuntimeSource identifies how a DSH runtime entered the catalog.
 */
export enum RuntimeSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeSourceManaged = "managed",
    RuntimeSourceDevelopmentFixture = "development-fixture",
    RuntimeSourceSystem = "system",
};

export interface Snapshot {
    "runtimes": RuntimeInfo[] | null;
    "dataDirectories": DataDirectoryInfo[] | null;
    "profiles": ProfileInfo[] | null;
    "configured"?: RunContext | null;
    "current"?: RunContext | null;
    "knownGood"?: RunContext | null;
    "theme": ThemePreference;
}

/**
 * ThemePreference is the DSH-owned appearance preference consumed by dsh-work's
 * trusted surfaces. dsh-work does not persist or edit this value.
 */
export enum ThemePreference {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemePreferenceLight = "light",
    ThemePreferenceDark = "dark",
    ThemePreferenceSystem = "system",
};
