// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lifecycle$0 from "../lifecycle/models.js";

/**
 * DSHReleaseInfo is cached public-registry metadata produced only by an
 * explicit refresh. It describes availability, not product compatibility.
 */
export interface DSHReleaseInfo {
    "version": string;
    "tags"?: string[] | null;
    "publishedAt"?: string;
    "source": RuntimeArtifactSource;
    "fallbackUsed": boolean;
    "observedAt": string;
}

/**
 * DataDirectoryInfo is a DSH_HOME identity. Profiles and their plugin state
 * live under a data directory and are never properties of a runtime.
 */
export interface DataDirectoryInfo {
    "id": string;
    "name": string;
    "path": string;
    "ownership": DataDirectoryOwnership;
}

/**
 * DataDirectoryOwnership describes who owns the DSH data directory. A
 * dsh-work-owned directory is safe for dsh-work to create and maintain; a
 * user-owned directory is discovered only.
 */
export enum DataDirectoryOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DataDirectoryOwnershipDSHWork = "dsh-work",
    DataDirectoryOwnershipUser = "user",
};

/**
 * LaunchRequest is the validation input used by both GUI and CLI callers.
 */
export interface LaunchRequest {
    "runtimeId": string;
    "node": NodeSelection;
    "profile": ProfileRef;
}

/**
 * LoaderEntry is one row of the loader tree. DefaultDisabled means the layers
 * turn it off outright; Conditional means a layer decides at load time.
 * Disabled means the profile's own patch layer turns it off.
 */
export interface LoaderEntry {
    "id": string;
    "package": string;
    "defaultDisabled"?: boolean;
    "conditional"?: boolean;
    "disabled"?: boolean;
}

export interface LoaderEntryDisableRequest {
    "target": PluginTarget;
    "id": string;
    "disabled": boolean;
}

export interface LoaderEntryListRequest {
    "target": PluginTarget;
}

/**
 * LoaderLayer is one official profile layer and the loader entries it
 * inserts into the profile's plugin tree.
 */
export interface LoaderLayer {
    "package": string;
    "entries": LoaderEntry[] | null;
}

/**
 * NodeInstallationInfo is one immutable managed installation or the current
 * system observation. Paths remain trusted-Settings data and are never copied
 * into acquisition provenance.
 */
export interface NodeInstallationInfo {
    "id": string;
    "version": string;
    "platform": string;
    "architecture": string;
    "nodePath": string;
    "npmPath": string;
    "pnpmPath"?: string;
    "ownership": NodeOwnership;
    "installSource": RuntimeArtifactSource;
    "sha256"?: string;
    "installed": boolean;
    "removable": boolean;
    "verified": boolean;
}

export enum NodeOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOwnershipSystem = "system",
    NodeOwnershipManaged = "managed",
};

/**
 * NodeReleaseInfo is the cached result of an explicit official release
 * refresh. Reading Snapshot never refreshes this record.
 */
export interface NodeReleaseInfo {
    "version": string;
    "platform": string;
    "architecture": string;
    "filename": string;
    "sha256": string;
    "source": RuntimeArtifactSource;
    "fallbackUsed": boolean;
    "observedAt": string;
}

export interface NodeSelection {
    "kind": NodeSelectionKind;
    "installationId"?: string;
}

export enum NodeSelectionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeSelectionSystem = "system",
    NodeSelectionManaged = "managed",
};

/**
 * PluginDisableRequest disables (or, with Disabled false, re-enables) one
 * installed plugin without uninstalling it.
 */
export interface PluginDisableRequest {
    "target": PluginTarget;
    "package": string;
    "disabled": boolean;
}

export interface PluginInfo {
    "name": string;
    "version"?: string;
    "package": string;
    "spec"?: string;
    "installed": boolean;
    "sourceKind": PluginSourceKind;
    "successfulRoute"?: RuntimeArtifactSource;
    "currentVersion"?: string;
    "availableVersion"?: string;
    "updateCheck": PluginUpdateCheck;

    /**
     * Disabled means the plugin stays installed but is kept out of the
     * profile's layer stack, so DSH does not load it.
     */
    "disabled"?: boolean;
}

export interface PluginInstallRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginListRequest {
    "target": PluginTarget;
}

export interface PluginRemoveRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginResult {
    "profile": ProfileRef;
    "plugins": PluginInfo[] | null;
    "restartRequired": boolean;
}

export enum PluginSourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PluginSourcePublicRegistry = "public-registry",
    PluginSourcePrivateRegistry = "private-registry",
    PluginSourceGit = "git",
    PluginSourceURL = "url",
    PluginSourceLocal = "local",
    PluginSourceUnknown = "unknown",
};

export interface PluginTarget {
    /**
     * Plugin state is scoped only by the DSH data directory and profile. The
     * manager resolves the current runtime at the mutation boundary.
     */
    "profile": ProfileRef;
}

export enum PluginUpdateCheck {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PluginUpdateUnknown = "unknown",
    PluginUpdateCurrent = "current",
    PluginUpdateAvailable = "available",
    PluginUpdateUnavailable = "unavailable",
};

export interface PluginUpgradeRequest {
    "target": PluginTarget;
    "package": string;
}

/**
 * ProfileBackupRequest selects the profile whose user-authored state should
 * be archived. Generated dependency trees and caches are excluded by the
 * backup implementation.
 */
export interface ProfileBackupRequest {
    "profile": ProfileRef;
}

export interface ProfileBackupResult {
    "profile": ProfileRef;
    "fileName": string;
    "size": number;
    "createdAt": string;
}

/**
 * ProfileCloneRequest copies an existing profile, including built-in profiles,
 * into a new unique profile directory. The manager owns the filesystem copy
 * because DSH does not expose a public clone command; generated state is
 * omitted and reconciled by DSH on the clone's next use.
 */
export interface ProfileCloneRequest {
    "profile": ProfileRef;
}

/**
 * ProfileCloneResult reports the new profile identity together with the
 * refreshed manager read model. It deliberately does not expose filesystem
 * paths to the UI.
 */
export interface ProfileCloneResult {
    "profile": ProfileRef;
    "snapshot": Snapshot;
}

/**
 * ProfileDeleteRequest removes one existing custom profile directory. Built-in
 * profiles, selected contexts and a retained failed-switch target are
 * protected by the manager.
 */
export interface ProfileDeleteRequest {
    "profile": ProfileRef;
}

/**
 * ProfileInfo is a read model. It does not compose or mutate DSH profiles;
 * those semantics remain behind the DSH public CLI seam.
 */
export interface ProfileInfo {
    "ref": ProfileRef;
    "path": string;
    "exists": boolean;
    "kind": ProfileKind;
    "launchable": boolean;
    "renamable": boolean;
    "deletable": boolean;
    "autoInitialize": boolean;
    "pluginCount": number;
    "plugins"?: PluginInfo[] | null;
}

export enum ProfileKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileKindBuiltIn = "built-in",
    ProfileKindCustom = "custom",
};

/**
 * ProfileRef is intentionally two-dimensional. A profile name is not unique
 * across DSH data directories, so every selection and plugin operation must
 * carry both the data-directory identity and the profile name.
 */
export interface ProfileRef {
    "dataDirectoryId": string;
    "name": string;
}

/**
 * ProfileRenameRequest changes the directory-backed identity of a custom DSH
 * profile. Built-in profile names belong to the DSH adapter and are immutable.
 */
export interface ProfileRenameRequest {
    "profile": ProfileRef;
    "newName": string;
}

export interface ProfileRestoreRequest {
    "dataDirectoryId": string;
    "fileName": string;
    "profileName": string;
}

export interface RecoveryOperation {
    "pointId": string;
    "stage": string;
    "status": string;
    "error"?: string;
    "resumeCount": number;
}

/**
 * ResolvedLaunch carries the validated catalog records alongside the
 * normalized target. Host uses this as one immutable handoff into the DSH
 * adapter, so it does not reconstruct data-directory/profile relationships
 * itself.
 */
export interface ResolvedLaunch {
    "target": RunContext;
    "runtime": RuntimeInfo;
    "node": ResolvedNode;
    "dataDirectory": DataDirectoryInfo;
}

export interface ResolvedNode {
    "selection": NodeSelection;
    "version": string;
    "nodePath": string;
    "npmPath"?: string;
    "pnpmPath"?: string;
    "childEnvironment"?: { [_ in string]?: string } | null;
}

export interface RestorePoint {
    "id": string;
    "kind": string;
    "label": string;
    "createdAt": string;
    "lastVerifiedAt": string;
    "target": RunContext;
    "dshVersion": string;
    "nodeVersion": string;
    "packageManager": string;
    "platform": string;
    "plugins": VersionPlugin[] | null;
    "digest": string;
    "lockfile"?: string;
    "unavailable"?: string;
}

export interface RestorePointsView {
    "points": RestorePoint[] | null;
    "lastByProfile": { [_ in string]?: string } | null;
    "lastRunning": string;
    "saveError"?: string;
    "operation"?: RecoveryOperation | null;
    "canSave": boolean;
}

export enum RollbackOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RollbackNotNeeded = "not-needed",
    RollbackRestored = "restored",
    RollbackDisabled = "disabled",
    RollbackFailed = "failed",
    RollbackUnavailable = "unavailable",
};

/**
 * RunContext is the complete dsh-work selection that defines one DSH Worker
 * generation. Runtime, DSH data directory and profile are one unit and cannot
 * be persisted or switched independently.
 */
export interface RunContext {
    "runtimeId": string;
    "node": NodeSelection;
    "profile": ProfileRef;
}

/**
 * RuntimeArtifactSource identifies the registry or carrier source used for a
 * managed runtime. It is separate from RuntimeSource, which describes catalog
 * ownership (managed, system or development fixture).
 */
export enum RuntimeArtifactSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeArtifactSourceNone = "none",
    RuntimeArtifactSourceLocal = "local",
    RuntimeArtifactSourceOfficial = "official",
    RuntimeArtifactSourceMirror = "mirror",
};

/**
 * RuntimeInfo is the platform-neutral read model for one immutable DSH
 * distribution. Path is the executable (or launcher) path, not a DSH data
 * directory.
 */
export interface RuntimeInfo {
    "id": string;
    "version": string;
    "path": string;
    "source": RuntimeSource;
    "toolchain"?: RuntimeToolchain;
    "installSource"?: RuntimeArtifactSource;
    "toolchainPath"?: string;
    "installed": boolean;
    "removable": boolean;
}

/**
 * RuntimeSource identifies how a DSH runtime entered the catalog.
 */
export enum RuntimeSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeSourceManaged = "managed",
    RuntimeSourceDevelopmentFixture = "development-fixture",
    RuntimeSourceSystem = "system",
};

/**
 * RuntimeToolchain identifies the toolchain used to materialize a managed
 * DSH runtime. dsh-work never installs a managed pnpm toolchain.
 */
export enum RuntimeToolchain {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeToolchainNone = "none",
    RuntimeToolchainSystemPNPM = "system-pnpm",
    RuntimeToolchainSystemNPM = "system-npm",
    RuntimeToolchainManagedNodeNPM = "managed-node-npm",
};

export interface SafeModeState {
    "target": RunContext;
    "returnTo": RunContext;
}

export interface Snapshot {
    "restorePoints"?: RestorePointsView | null;
    "safeMode"?: SafeModeState | null;
    "runtimes": RuntimeInfo[] | null;
    "dshReleases": DSHReleaseInfo[] | null;
    "nodes": NodeInstallationInfo[] | null;
    "systemNode"?: ResolvedNode | null;
    "latestNode"?: NodeReleaseInfo | null;
    "dataDirectories": DataDirectoryInfo[] | null;
    "profiles": ProfileInfo[] | null;
    "configured"?: RunContext | null;
    "current"?: RunContext | null;
    "knownGood"?: RunContext | null;
    "lastSwitchAttempt"?: SwitchAttempt | null;
    "theme": ThemePreference;
}

/**
 * SwitchAttempt is the one bounded terminal result retained for recovery. It
 * is persisted with the recovery point and never mutates a runtime installation.
 */
export interface SwitchAttempt {
    "target": RunContext;
    "stage": SwitchAttemptStage;
    "failure": lifecycle$0.Failure;
    "automaticRollback": boolean;
    "rollback": RollbackOutcome;
    "rollbackFailure"?: lifecycle$0.Failure | null;
    "completedAt": string;
}

export enum SwitchAttemptStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SwitchAttemptResolving = "resolving",
    SwitchAttemptCandidate = "candidate",
    SwitchAttemptRollback = "rollback",
};

/**
 * ThemePreference is the DSH-owned appearance preference consumed by dsh-work's
 * trusted surfaces. dsh-work does not persist or edit this value.
 */
export enum ThemePreference {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemePreferenceLight = "light",
    ThemePreferenceDark = "dark",
    ThemePreferenceSystem = "system",
};

export interface VersionPlugin {
    "name": string;
    "version": string;
    "source": string;
    "group": string;
}
