// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostService is the intentionally narrow Wails binding surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lifecycle$0 from "../lifecycle/models.js";

export function Cancel(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(2192368078);
}

export function GetStatus(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3548614106);
}

export function Quit(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(336297499);
}

export function Restart(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(3788146135);
}

export function Start(): $CancellablePromise<lifecycle$0.Status> {
    return $Call.ByID(265946144);
}
