// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagerService is the trusted Manager-window binding. It exposes catalog,
 * selection, runtime/home and profile-plugin operations; profile composition
 * and plugin mutation still go through DSH's public CLI seam, never direct
 * file edits.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";

export function GetSnapshot(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3103025421);
}

export function InstallPlugin(request: dshmanager$0.PluginInstallRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(1130688437, request);
}

export function InstallRuntime(version: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3933820354, version);
}

export function ListPlugins(request: dshmanager$0.PluginListRequest): $CancellablePromise<dshmanager$0.PluginInfo[] | null> {
    return $Call.ByID(2864409457, request);
}

export function RegisterHome(home: dshmanager$0.HomeInfo): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2936117313, home);
}

export function RemoveHome(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3573879260, id);
}

export function RemovePlugin(request: dshmanager$0.PluginRemoveRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(547869100, request);
}

export function RemoveRuntime(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3251481673, id);
}

export function ResolveLaunch(request: dshmanager$0.LaunchRequest): $CancellablePromise<dshmanager$0.ResolvedLaunch> {
    return $Call.ByID(1105056358, request);
}

export function SetDesiredSelection(selection: dshmanager$0.LaunchSelection): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1044943993, selection);
}
