// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagerService is the trusted Settings-window binding for the nested DSH
 * manager. It exposes catalog, Run-context, runtime/data-directory and
 * profile-plugin operations; profile composition and plugin mutation still go
 * through DSH's public CLI seam, never direct file edits.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dshmanager$0 from "../dshmanager/models.js";

export function GetSnapshot(): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3103025421);
}

/**
 * GetTheme reads the selected DSH data directory's appearance preference. Settings uses
 * it while both trusted windows are open so its surface follows changes made
 * by DSH.
 */
export function GetTheme(): $CancellablePromise<dshmanager$0.ThemePreference> {
    return $Call.ByID(2854035570);
}

export function InstallPlugin(request: dshmanager$0.PluginInstallRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(1130688437, request);
}

export function InstallRuntime(version: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3933820354, version);
}

export function ListPlugins(request: dshmanager$0.PluginListRequest): $CancellablePromise<dshmanager$0.PluginInfo[] | null> {
    return $Call.ByID(2864409457, request);
}

export function RegisterDataDirectory(dataDirectory: dshmanager$0.DataDirectoryInfo): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(4210621493, dataDirectory);
}

export function RemoveDataDirectory(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(1955812790, id);
}

export function RemovePlugin(request: dshmanager$0.PluginRemoveRequest): $CancellablePromise<dshmanager$0.PluginResult> {
    return $Call.ByID(547869100, request);
}

export function RemoveRuntime(id: string): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3251481673, id);
}

export function RenameProfile(request: dshmanager$0.ProfileRenameRequest): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(2306798674, request);
}

export function ResolveLaunch(request: dshmanager$0.LaunchRequest): $CancellablePromise<dshmanager$0.ResolvedLaunch> {
    return $Call.ByID(1105056358, request);
}

export function SetRunContext(target: dshmanager$0.RunContext): $CancellablePromise<dshmanager$0.Snapshot> {
    return $Call.ByID(3523733425, target);
}
