// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the trusted top-level Settings surface. It exposes only
 * real persisted preferences; unsupported future toggles are not represented
 * as fake frontend controls. DSH manager controls share this Settings window
 * but remain a separate service boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

export function GetSettings(): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(3226009084);
}

export function SetCloseToTray(enabled: boolean): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(3879396778, enabled);
}

export function SetLocale(locale: string): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(2263426239, locale);
}

export function SetNotificationPreference(key: string, enabled: boolean): $CancellablePromise<settings$0.Values> {
    return $Call.ByID(4030491503, key, enabled);
}
