// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspacecontext$0 from "../workspacecontext/models.js";

/**
 * ErrorCode is the stable dsh-work error vocabulary. Dependency-specific detail
 * stays at the Adapter boundary and is never used as a UI control protocol.
 */
export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorInvalidTransition = "INVALID_LIFECYCLE_TRANSITION",
    ErrorPlatformUnsupported = "PLATFORM_UNSUPPORTED",
    ErrorDSHRuntimeNotFound = "DSH_RUNTIME_NOT_FOUND",
    ErrorDSHVersionCheckFailed = "DSH_VERSION_CHECK_FAILED",
    ErrorDSHUnsupportedVersion = "DSH_UNSUPPORTED_VERSION",
    ErrorDSHStartFailed = "DSH_START_FAILED",
    ErrorDSHEarlyExit = "DSH_EARLY_EXIT",
    ErrorDSHReadinessTimeout = "DSH_READINESS_TIMEOUT",
    ErrorDSHInvalidReadiness = "DSH_INVALID_READINESS",
    ErrorGatewayUnavailable = "WORKER_GATEWAY_UNAVAILABLE",
    ErrorGatewayStartFailed = "WORKER_GATEWAY_START_FAILED",
    ErrorGatewayCloseFailed = "WORKER_GATEWAY_CLOSE_FAILED",
    ErrorProcessStartFailed = "PROCESS_START_FAILED",
    ErrorProcessCleanupFailed = "PROCESS_CLEANUP_FAILED",
    ErrorProcessStopFailed = "PROCESS_STOP_FAILED",
    ErrorCancelled = "CANCELLED",
    ErrorProfileRequired = "PROFILE_REQUIRED",
    ErrorProfileNotFound = "PROFILE_NOT_FOUND",
    ErrorProfileInvalid = "PROFILE_INVALID",
    ErrorProfileInUse = "PROFILE_IN_USE",
    ErrorProfileRenameFailed = "PROFILE_RENAME_FAILED",
    ErrorProfileCloneFailed = "PROFILE_CLONE_FAILED",
    ErrorProfileDeleteFailed = "PROFILE_DELETE_FAILED",
    ErrorProfileBackupFailed = "PROFILE_BACKUP_FAILED",
    ErrorProfilePreparationFailed = "PROFILE_PREPARATION_FAILED",
    ErrorWorkspaceInvalid = "WORKSPACE_INVALID",
    ErrorRuntimeInUse = "RUNTIME_IN_USE",
    ErrorRuntimeProfileIncompatible = "RUNTIME_PROFILE_INCOMPATIBLE",
    ErrorManagerOperationBusy = "MANAGER_OPERATION_BUSY",
    ErrorManagerStateInvalid = "MANAGER_STATE_INVALID",
    ErrorSettingsStateInvalid = "SETTINGS_STATE_INVALID",
    ErrorSettingsUnavailable = "SETTINGS_UNAVAILABLE",
    ErrorNotificationDeliveryFailed = "NOTIFICATION_DELIVERY_FAILED",
    ErrorRestartRequired = "RESTART_REQUIRED",
    ErrorPluginSpecInvalid = "PLUGIN_SPEC_INVALID",
    ErrorPluginCommandUnavailable = "PLUGIN_COMMAND_UNAVAILABLE",
    ErrorPluginCommandFailed = "PLUGIN_COMMAND_FAILED",
    ErrorRuntimeInstallUnavailable = "RUNTIME_INSTALL_UNAVAILABLE",
    ErrorRuntimeInstallFailed = "RUNTIME_INSTALL_FAILED",
    ErrorTrustedSurfaceRequired = "TRUSTED_SURFACE_REQUIRED",
};

/**
 * Failure is safe to project to the trusted UI. Detail is bounded diagnostic
 * context and must already be redacted by the producing Adapter.
 */
export interface Failure {
    "code": ErrorCode;
    "summary": string;
    "retryable": boolean;
    "effectOccurred": boolean;
    "correlationId": string;
    "detail"?: string;
}

/**
 * Phase identifies the bounded startup or shutdown step currently in progress.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhaseIdle = "idle",
    PhaseConfiguration = "configuration",
    PhaseRuntime = "runtime",
    PhaseWorker = "worker",
    PhaseReadiness = "readiness",
    PhaseWorkspace = "workspace",
    PhaseStopping = "stopping",
    PhaseFailed = "failed",
};

/**
 * RuntimePreparation is a bounded status projection for the trusted Host UI.
 * TotalBytes is meaningful only when HasTotal is true; zero never means that a
 * download is complete.
 */
export interface RuntimePreparation {
    "state": RuntimePreparationState;
    "operation": RuntimePreparationOperation;
    "targetVersion"?: string;
    "toolchain"?: string;
    "source": RuntimePreparationSource;
    "receivedBytes"?: number;
    "totalBytes"?: number;
    "hasTotal": boolean;
    "canCancel": boolean;
    "error"?: Failure | null;
}

/**
 * RuntimePreparationOperation identifies the user-relevant operation in a
 * preparation state. The frontend maps these values to localized copy.
 */
export enum RuntimePreparationOperation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimePreparationOperationNone = "none",
    RuntimePreparationOperationDetectNode = "detect-node",
    RuntimePreparationOperationDetectPNPM = "detect-pnpm",
    RuntimePreparationOperationDetectNPM = "detect-npm",
    RuntimePreparationOperationDownloadNode = "download-node",
    RuntimePreparationOperationInstallDSH = "install-dsh",
    RuntimePreparationOperationVerify = "verify",
    RuntimePreparationOperationCleanup = "cleanup",
};

/**
 * RuntimePreparationSource records which approved source supplied the current
 * artifact. A mirror is only exposed after the official source was unreachable.
 */
export enum RuntimePreparationSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimePreparationSourceNone = "none",
    RuntimePreparationSourceLocal = "local",
    RuntimePreparationSourceOfficial = "official",
    RuntimePreparationSourceMirror = "mirror",
};

/**
 * RuntimePreparationState is the safe, typed projection of an explicit or
 * first-use DSH runtime acquisition. It contains no command lines, paths or
 * raw package-manager output.
 */
export enum RuntimePreparationState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimePreparationIdle = "idle",
    RuntimePreparationResolvingToolchain = "resolving-toolchain",
    RuntimePreparationAcquiringNode = "acquiring-node",
    RuntimePreparationAcquiringDSH = "acquiring-dsh",
    RuntimePreparationVerifying = "verifying",
    RuntimePreparationInstalled = "installed",
    RuntimePreparationCancelled = "cancelled",
    RuntimePreparationFailed = "failed",
};

/**
 * State is the platform-neutral lifecycle state projected to the trusted UI.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateStarting = "Starting",
    StateReady = "Ready",
    StateStopping = "Stopping",
    StateStopped = "Stopped",
    StateFailed = "Failed",
};

/**
 * Status is the immutable read model consumed by the frontend.
 */
export interface Status {
    "state": State;
    "phase": Phase;
    "generationId"?: string;
    "workspaceUrl"?: string;
    "workspace"?: workspacecontext$0.Context | null;
    "runtimePreparation"?: RuntimePreparation | null;
    "error"?: Failure | null;
    "canRetry": boolean;
    "canCancel": boolean;
    "correlationId"?: string;
}
