// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HomeInfo is a DSH_HOME identity. Profiles and their plugin state live under
 * a home and are never properties of a runtime.
 */
export interface HomeInfo {
    "id": string;
    "name": string;
    "path": string;
    "ownership": HomeOwnership;
}

/**
 * HomeOwnership describes who owns the DSH home. A Work-owned home is safe
 * for dsh-work to create and maintain; a user-owned home is discovered only.
 */
export enum HomeOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HomeOwnershipWork = "work",
    HomeOwnershipUser = "user",
};

/**
 * LaunchRequest is the validation input used by both GUI and CLI callers.
 */
export interface LaunchRequest {
    "runtimeId": string;
    "profile": ProfileRef;
    "workspace": string;
}

/**
 * LaunchSelection is the persisted desired state and the active state
 * projected to the manager window. Workspace is deliberately separate from
 * the profile so one profile can be used for multiple projects.
 */
export interface LaunchSelection {
    "runtimeId": string;
    "profile": ProfileRef;
    "workspace": string;
}

export interface PluginInfo {
    "name": string;
    "version"?: string;
    "package": string;
    "spec"?: string;
    "installed": boolean;
}

export interface PluginInstallRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginListRequest {
    "target": PluginTarget;
}

export interface PluginRemoveRequest {
    "target": PluginTarget;
    "package": string;
}

export interface PluginResult {
    "profile": ProfileRef;
    "plugins": PluginInfo[] | null;
    "restartRequired": boolean;
}

export interface PluginTarget {
    "runtimeId": string;
    "profile": ProfileRef;
}

/**
 * ProfileInfo is a read model. It does not compose or mutate DSH profiles;
 * those semantics remain behind the DSH public CLI seam.
 */
export interface ProfileInfo {
    "ref": ProfileRef;
    "path": string;
    "exists": boolean;
    "kind": ProfileKind;
    "launchable": boolean;
    "autoInitialize": boolean;
    "pluginCount": number;
    "plugins"?: PluginInfo[] | null;
}

export enum ProfileKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileKindBuiltIn = "built-in",
    ProfileKindCustom = "custom",
};

/**
 * ProfileRef is intentionally two-dimensional. A profile name is not unique
 * across DSH homes, so every selection and plugin operation must carry both
 * the home identity and the profile name.
 */
export interface ProfileRef {
    "homeId": string;
    "name": string;
}

/**
 * ResolvedLaunch carries the validated catalog records alongside the
 * normalized selection. Host uses this as one immutable handoff into the DSH
 * adapter, so it does not reconstruct home/profile relationships itself.
 */
export interface ResolvedLaunch {
    "selection": LaunchSelection;
    "runtime": RuntimeInfo;
    "home": HomeInfo;
}

/**
 * RuntimeInfo is the platform-neutral read model for one immutable DSH
 * distribution. Path is the executable (or launcher) path, not a DSH home.
 */
export interface RuntimeInfo {
    "id": string;
    "version": string;
    "path": string;
    "source": RuntimeSource;
    "installed": boolean;
    "removable": boolean;
}

/**
 * RuntimeSource identifies how a DSH runtime entered the catalog.
 */
export enum RuntimeSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeSourceManaged = "managed",
    RuntimeSourceDevelopmentFixture = "development-fixture",
    RuntimeSourceSystem = "system",
};

export interface Snapshot {
    "runtimes": RuntimeInfo[] | null;
    "homes": HomeInfo[] | null;
    "profiles": ProfileInfo[] | null;
    "desired"?: LaunchSelection | null;
    "active"?: LaunchSelection | null;
}
