// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Activity {
    "sessionId": string;
    "parentSessionId"?: string;
    "title": string;
    "seq": number;
    "turn": number;
    "running": boolean;
    "outcome": string;
    "summary": string;
    "unread": boolean;
    "updatedAt": number;
    "interaction"?: Interaction | null;
    "goal"?: Goal | null;
    "queued": number;
    "steering": number;
    "jobs": Job[] | null;
    "state": string;
}

export interface Goal {
    "phase": string;
    "objective": string;
    "reason": string;
    "rounds": number;
    "maxRounds": number;
}

export interface Interaction {
    "key": string;
    "kind": string;
    "text": string;
    "count": number;
}

export interface Job {
    "id": string;
    "label": string;
    "status": string;
    "detail": string;
}

export interface Snapshot {
    "schemaVersion": number;
    "generation": string;
    "revision": number;
    "sessions": Activity[] | null;
    "connected": boolean;
    "navigationError"?: string;
}
