// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInstallMode tells the UI which explicit install action is available.
 * The first desktop slice uses staged-restart; installer is reserved for a
 * future package-backed release source.
 */
export enum UpdateInstallMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UpdateInstallNone = "",
    UpdateInstallStagedRestart = "staged-restart",
    UpdateInstallInstaller = "installer",
};

/**
 * UpdatePhase is the user-visible phase of the daemon-owned application
 * updater. The desktop UI renders this state; it does not infer updater state
 * from local process or temporary-file details.
 */
export enum UpdatePhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UpdateUnconfigured = "unconfigured",
    UpdateIdle = "idle",
    UpdateChecking = "checking",
    UpdateUpToDate = "up-to-date",
    UpdateAvailable = "available",
    UpdateDownloading = "downloading",
    UpdateVerifying = "verifying",
    UpdateReady = "ready",
    UpdateInstalling = "installing",
    UpdateError = "error",
};

/**
 * UpdateSnapshot is safe to expose over the trusted local IPC boundary. It
 * deliberately omits provider internals, staging paths and raw errors.
 */
export interface UpdateSnapshot {
    "phase": UpdatePhase;
    "currentVersion": string;
    "targetVersion"?: string;
    "receivedBytes"?: number;
    "totalBytes"?: number;
    "lastCheckedAt"?: string;
    "errorCode"?: string;
    "installMode": UpdateInstallMode;
}
