// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Locale is the Work-owned language preference. It is deliberately separate
 * from DSH's appearance preference: DSH owns theme, while Work owns its own
 * chrome and settings copy.
 */
export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleEnglish = "en",
    LocaleChinese = "zh-CN",
    LocaleJapanese = "ja-JP",
    DefaultLocale = "zh-CN",
};

/**
 * Values is the versioned, platform-neutral Work preference contract.
 * CloseToTray is true by default so closing the last window keeps Work and
 * its managed DSH worker available from the notification area.
 */
export interface Values {
    "version": number;
    "closeToTray": boolean;
    "locale": Locale;
}
