// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Locations {
    "root": string;

    /**
     * Empty means follow Root/user-data, including when Root is moved.
     */
    "userData": string;
}

export interface State {
    "current": Locations;
    "pending"?: Locations | null;
    "error"?: string;
}
