// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../notifications/models.js";

/**
 * Appearance is the Host-owned look of the startup, Settings and Pet settings
 * surfaces. DSH content keeps its own appearance.
 */
export interface Appearance {
    "theme": ThemeID;
    "mode": AppearanceMode;
}

/**
 * AppearanceMode is the light/dark choice for dsh-work's own windows.
 */
export enum AppearanceMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AppearanceSystem = "system",
    AppearanceLight = "light",
    AppearanceDark = "dark",
};

/**
 * Locale is the dsh-work-owned language for its own chrome and settings copy.
 */
export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleEnglish = "en",
    LocaleChinese = "zh-CN",
    LocaleJapanese = "ja-JP",
    DefaultLocale = "zh-CN",
};

/**
 * PetPosition stores a monitor-aware logical anchor rather than an absolute
 * screen coordinate. Host policy clamps it to the current work area.
 */
export interface PetPosition {
    "monitorId"?: string;
    "anchorX": number;
    "anchorY": number;
    "width": number;
    "height": number;
    "scale": number;
}

/**
 * PetPreference is the versioned Host-owned Pet preference. A missing
 * selected key is represented by nil and is never replaced by discovery.
 */
export interface PetPreference {
    "schemaVersion": number;
    "selectedKey": string | null;
    "visibilityIntent": PetVisibilityIntent;
    "alwaysOnTop": boolean;
    "position": PetPosition;
}

/**
 * PetVisibilityIntent is the persisted user choice. It is intentionally
 * separate from the runtime's effective visibility, which can be paused when
 * the selected package is unavailable or the platform cannot host an overlay.
 */
export enum PetVisibilityIntent {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PetVisibilityVisible = "visible",
    PetVisibilityHidden = "hidden",
};

/**
 * ThemeID names a built-in dsh-work theme. Themes are static and shipped with
 * the frontend; the Host only stores which one the user chose.
 */
export enum ThemeID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeMonochrome = "monochrome",
    ThemeChatGPT = "chatgpt",
    ThemeClaude = "claude",
    ThemeGitHub = "github",
    ThemeLobeHub = "lobehub",
    ThemeSoft = "soft",
    ThemeSwiss = "swiss",
    ThemePaper = "paper",
    ThemeGlass = "glass",
    ThemeInk = "ink",
    ThemeClassic = "classic",
    ThemeTerminal = "terminal",
    ThemeNeon = "neon",
    ThemeBrutal = "brutal",
    ThemeBauhaus = "bauhaus",
    ThemeDeco = "deco",
    DefaultTheme = "monochrome",
};

/**
 * Values is the versioned, platform-neutral dsh-work preference contract.
 */
export interface Values {
    "workspaceWindow": WindowGeometry;
    "settingsWindow": WindowGeometry;
    "version": number;
    "automaticRuntimeRollback": boolean;
    "locale": Locale;
    "notifications": notifications$0.Preferences;
    "pet": PetPreference;
    "appearance": Appearance;
}

/**
 * Width and Height are logical normal-window dimensions, independent of maximisation.
 */
export interface WindowGeometry {
    "width": number;
    "height": number;
    "maximised": boolean;
}
