// Code generated by scripts/generate-daemon-client.py; DO NOT EDIT.
package desktopclient

import (
	"context"
	"github.com/local/dsh-work/internal/app"
	"github.com/local/dsh-work/internal/daemon"
	"github.com/local/dsh-work/internal/dshmanager"
)

type ManagerService struct {
	Client *daemon.Client
	Local  *app.ManagerService
}

func (s *ManagerService) RegisterRuntime(ctx context.Context, runtime dshmanager.RuntimeInfo) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RegisterRuntime(ctx, runtime)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RegisterRuntime", []any{runtime}, &value)
	return value, err
}

func (s *ManagerService) GetSnapshot(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.GetSnapshot(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "GetSnapshot", []any{}, &value)
	return value, err
}

func (s *ManagerService) GetTheme(ctx context.Context) dshmanager.ThemePreference {
	if s.Local != nil {
		return s.Local.GetTheme(ctx)
	}
	var value dshmanager.ThemePreference
	err := call(ctx, s.Client, "ManagerService", "GetTheme", []any{}, &value)
	if err != nil {
		panic(err)
	}
	return value
}

func (s *ManagerService) SetRunContext(ctx context.Context, target dshmanager.RunContext) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.SetRunContext(ctx, target)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "SetRunContext", []any{target}, &value)
	return value, err
}

func (s *ManagerService) RetryLastSwitch(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RetryLastSwitch(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RetryLastSwitch", []any{}, &value)
	return value, err
}

func (s *ManagerService) RestoreKnownGood(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RestoreKnownGood(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RestoreKnownGood", []any{}, &value)
	return value, err
}

func (s *ManagerService) InstallRuntime(ctx context.Context, version string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.InstallRuntime(ctx, version)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "InstallRuntime", []any{version}, &value)
	return value, err
}

func (s *ManagerService) RefreshLatestNode(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RefreshLatestNode(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RefreshLatestNode", []any{}, &value)
	return value, err
}

func (s *ManagerService) RefreshDSHReleases(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RefreshDSHReleases(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RefreshDSHReleases", []any{}, &value)
	return value, err
}

func (s *ManagerService) InstallLatestNode(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.InstallLatestNode(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "InstallLatestNode", []any{}, &value)
	return value, err
}

func (s *ManagerService) RemoveNode(ctx context.Context, id string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RemoveNode(ctx, id)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RemoveNode", []any{id}, &value)
	return value, err
}

func (s *ManagerService) CancelRuntime(ctx context.Context) error {
	if s.Local != nil {
		return s.Local.CancelRuntime(ctx)
	}
	err := call(ctx, s.Client, "ManagerService", "CancelRuntime", []any{}, nil)
	return err
}

func (s *ManagerService) CancelAcquisition(ctx context.Context) error {
	if s.Local != nil {
		return s.Local.CancelAcquisition(ctx)
	}
	err := call(ctx, s.Client, "ManagerService", "CancelAcquisition", []any{}, nil)
	return err
}

func (s *ManagerService) RemoveRuntime(ctx context.Context, id string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RemoveRuntime(ctx, id)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RemoveRuntime", []any{id}, &value)
	return value, err
}

func (s *ManagerService) RegisterDataDirectory(ctx context.Context, dataDirectory dshmanager.DataDirectoryInfo) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RegisterDataDirectory(ctx, dataDirectory)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RegisterDataDirectory", []any{dataDirectory}, &value)
	return value, err
}

func (s *ManagerService) RemoveDataDirectory(ctx context.Context, id string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RemoveDataDirectory(ctx, id)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RemoveDataDirectory", []any{id}, &value)
	return value, err
}

func (s *ManagerService) ResolveLaunch(ctx context.Context, request dshmanager.LaunchRequest) (dshmanager.ResolvedLaunch, error) {
	if s.Local != nil {
		return s.Local.ResolveLaunch(ctx, request)
	}
	var value dshmanager.ResolvedLaunch
	err := call(ctx, s.Client, "ManagerService", "ResolveLaunch", []any{request}, &value)
	return value, err
}

func (s *ManagerService) ListPlugins(ctx context.Context, request dshmanager.PluginListRequest) ([]dshmanager.PluginInfo, error) {
	if s.Local != nil {
		return s.Local.ListPlugins(ctx, request)
	}
	var value []dshmanager.PluginInfo
	err := call(ctx, s.Client, "ManagerService", "ListPlugins", []any{request}, &value)
	return value, err
}

func (s *ManagerService) InstallPlugin(ctx context.Context, request dshmanager.PluginInstallRequest) (result dshmanager.PluginResult, resultErr error) {
	if s.Local != nil {
		return s.Local.InstallPlugin(ctx, request)
	}
	var value dshmanager.PluginResult
	err := call(ctx, s.Client, "ManagerService", "InstallPlugin", []any{request}, &value)
	return value, err
}

func (s *ManagerService) RemovePlugin(ctx context.Context, request dshmanager.PluginRemoveRequest) (result dshmanager.PluginResult, resultErr error) {
	if s.Local != nil {
		return s.Local.RemovePlugin(ctx, request)
	}
	var value dshmanager.PluginResult
	err := call(ctx, s.Client, "ManagerService", "RemovePlugin", []any{request}, &value)
	return value, err
}

func (s *ManagerService) SetPluginDisabled(ctx context.Context, request dshmanager.PluginDisableRequest) (result dshmanager.PluginResult, resultErr error) {
	if s.Local != nil {
		return s.Local.SetPluginDisabled(ctx, request)
	}
	var value dshmanager.PluginResult
	err := call(ctx, s.Client, "ManagerService", "SetPluginDisabled", []any{request}, &value)
	return value, err
}

func (s *ManagerService) UpgradePlugin(ctx context.Context, request dshmanager.PluginUpgradeRequest) (result dshmanager.PluginResult, resultErr error) {
	if s.Local != nil {
		return s.Local.UpgradePlugin(ctx, request)
	}
	var value dshmanager.PluginResult
	err := call(ctx, s.Client, "ManagerService", "UpgradePlugin", []any{request}, &value)
	return value, err
}

func (s *ManagerService) RenameProfile(ctx context.Context, request dshmanager.ProfileRenameRequest) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RenameProfile(ctx, request)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RenameProfile", []any{request}, &value)
	return value, err
}

func (s *ManagerService) CloneProfile(ctx context.Context, request dshmanager.ProfileCloneRequest) (dshmanager.ProfileCloneResult, error) {
	if s.Local != nil {
		return s.Local.CloneProfile(ctx, request)
	}
	var value dshmanager.ProfileCloneResult
	err := call(ctx, s.Client, "ManagerService", "CloneProfile", []any{request}, &value)
	return value, err
}

func (s *ManagerService) DeleteProfile(ctx context.Context, request dshmanager.ProfileDeleteRequest) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.DeleteProfile(ctx, request)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "DeleteProfile", []any{request}, &value)
	return value, err
}

func (s *ManagerService) BackupProfile(ctx context.Context, request dshmanager.ProfileBackupRequest) (dshmanager.ProfileBackupResult, error) {
	if s.Local != nil {
		return s.Local.BackupProfile(ctx, request)
	}
	var value dshmanager.ProfileBackupResult
	err := call(ctx, s.Client, "ManagerService", "BackupProfile", []any{request}, &value)
	return value, err
}

func (s *ManagerService) ListProfileBackups(ctx context.Context, ref dshmanager.ProfileRef) ([]dshmanager.ProfileBackupResult, error) {
	if s.Local != nil {
		return s.Local.ListProfileBackups(ctx, ref)
	}
	var value []dshmanager.ProfileBackupResult
	err := call(ctx, s.Client, "ManagerService", "ListProfileBackups", []any{ref}, &value)
	return value, err
}

func (s *ManagerService) DeleteProfileBackup(ctx context.Context, ref dshmanager.ProfileRef, fileName string) error {
	if s.Local != nil {
		return s.Local.DeleteProfileBackup(ctx, ref, fileName)
	}
	err := call(ctx, s.Client, "ManagerService", "DeleteProfileBackup", []any{ref, fileName}, nil)
	return err
}

func (s *ManagerService) RestoreProfileBackup(ctx context.Context, request dshmanager.ProfileRestoreRequest) (dshmanager.ProfileCloneResult, error) {
	if s.Local != nil {
		return s.Local.RestoreProfileBackup(ctx, request)
	}
	var value dshmanager.ProfileCloneResult
	err := call(ctx, s.Client, "ManagerService", "RestoreProfileBackup", []any{request}, &value)
	return value, err
}

func (s *ManagerService) ImportProfileBackup(ctx context.Context) (*dshmanager.ProfileCloneResult, error) {
	if s.Local != nil {
		return s.Local.ImportProfileBackup(ctx)
	}
	var value *dshmanager.ProfileCloneResult
	err := call(ctx, s.Client, "ManagerService", "ImportProfileBackup", []any{}, &value)
	return value, err
}

func (s *ManagerService) OpenProfileBackups(ctx context.Context, ref dshmanager.ProfileRef) error {
	if s.Local != nil {
		return s.Local.OpenProfileBackups(ctx, ref)
	}
	err := call(ctx, s.Client, "ManagerService", "OpenProfileBackups", []any{ref}, nil)
	return err
}

func (s *ManagerService) EnterSafeMode(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.EnterSafeMode(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "EnterSafeMode", []any{}, &value)
	return value, err
}

func (s *ManagerService) ExitSafeMode(ctx context.Context) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.ExitSafeMode(ctx)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "ExitSafeMode", []any{}, &value)
	return value, err
}

func (s *ManagerService) ExportProfile(ctx context.Context, ref dshmanager.ProfileRef) (string, error) {
	if s.Local != nil {
		return s.Local.ExportProfile(ctx, ref)
	}
	var value string
	err := call(ctx, s.Client, "ManagerService", "ExportProfile", []any{ref}, &value)
	return value, err
}

func (s *ManagerService) SaveRestorePoint(ctx context.Context, label string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.SaveRestorePoint(ctx, label)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "SaveRestorePoint", []any{label}, &value)
	return value, err
}

func (s *ManagerService) RenameRestorePoint(ctx context.Context, id, label string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RenameRestorePoint(ctx, id, label)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RenameRestorePoint", []any{id, label}, &value)
	return value, err
}

func (s *ManagerService) DeleteRestorePoint(ctx context.Context, id string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.DeleteRestorePoint(ctx, id)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "DeleteRestorePoint", []any{id}, &value)
	return value, err
}

func (s *ManagerService) PreviewRestorePoint(ctx context.Context, id string) (dshmanager.RestorePoint, error) {
	if s.Local != nil {
		return s.Local.PreviewRestorePoint(ctx, id)
	}
	var value dshmanager.RestorePoint
	err := call(ctx, s.Client, "ManagerService", "PreviewRestorePoint", []any{id}, &value)
	return value, err
}

func (s *ManagerService) RestorePoint(ctx context.Context, id string) (dshmanager.Snapshot, error) {
	if s.Local != nil {
		return s.Local.RestorePoint(ctx, id)
	}
	var value dshmanager.Snapshot
	err := call(ctx, s.Client, "ManagerService", "RestorePoint", []any{id}, &value)
	return value, err
}

func (s *ManagerService) CancelRestore(ctx context.Context) error {
	if s.Local != nil {
		return s.Local.CancelRestore(ctx)
	}
	err := call(ctx, s.Client, "ManagerService", "CancelRestore", []any{}, nil)
	return err
}
