// Code generated by scripts/generate-daemon-client.py; DO NOT EDIT.
package desktopclient

import (
	"context"
	"github.com/local/dsh-work/internal/app"
	"github.com/local/dsh-work/internal/daemon"
	"github.com/local/dsh-work/internal/lifecycle"
	"github.com/local/dsh-work/internal/pet"
)

type PetSettingsService struct {
	Client      *daemon.Client
	Local       *app.PetSettingsService
	Maintenance func() bool
}

func (s *PetSettingsService) localMaintenanceFailure() error {
	if s.Maintenance == nil || !s.Maintenance() {
		return nil
	}
	return lifecycle.Failure{Code: lifecycle.ErrorManagerOperationBusy, Summary: "dsh-work is being updated.", Retryable: true, CorrelationID: lifecycle.NewCorrelationID(), Detail: "Wait for the installer to finish, then retry the Pet action."}
}

func (s *PetSettingsService) SetPetHitRegions(ctx context.Context, regions []app.PetHitRegion) error {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return err
		}
		return s.Local.SetPetHitRegions(ctx, regions)
	}
	err := call(ctx, s.Client, "PetSettingsService", "SetPetHitRegions", []any{regions}, nil)
	return err
}

func (s *PetSettingsService) GetPetPlayback(ctx context.Context, known string) (*pet.Playback, error) {
	if s.Local != nil {
		return s.Local.GetPetPlayback(ctx, known)
	}
	var value *pet.Playback
	err := call(ctx, s.Client, "PetSettingsService", "GetPetPlayback", []any{known}, &value)
	return value, err
}

func (s *PetSettingsService) PetGesture(ctx context.Context, kind string, x, y float64) error {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return err
		}
		return s.Local.PetGesture(ctx, kind, x, y)
	}
	err := call(ctx, s.Client, "PetSettingsService", "PetGesture", []any{kind, x, y}, nil)
	return err
}

func (s *PetSettingsService) OpenPetActivity(ctx context.Context, sessionID string) error {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return err
		}
		return s.Local.OpenPetActivity(ctx, sessionID)
	}
	err := call(ctx, s.Client, "PetSettingsService", "OpenPetActivity", []any{sessionID}, nil)
	return err
}

func (s *PetSettingsService) SetPetReducedMotion(ctx context.Context, enabled bool) error {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return err
		}
		return s.Local.SetPetReducedMotion(ctx, enabled)
	}
	err := call(ctx, s.Client, "PetSettingsService", "SetPetReducedMotion", []any{enabled}, nil)
	return err
}

func (s *PetSettingsService) GetPetPanel(ctx context.Context) (app.PetPanel, error) {
	if s.Local != nil {
		return s.Local.GetPetPanel(ctx)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "GetPetPanel", []any{}, &value)
	return value, err
}

func (s *PetSettingsService) GetPetOverlay(ctx context.Context) (app.PetOverlayState, error) {
	if s.Local != nil {
		return s.Local.GetPetOverlay(ctx)
	}
	var value app.PetOverlayState
	err := call(ctx, s.Client, "PetSettingsService", "GetPetOverlay", []any{}, &value)
	return value, err
}

func (s *PetSettingsService) GetPetPresentation(ctx context.Context) (app.PetOverlayState, error) {
	if s.Local != nil {
		return s.Local.GetPetPresentation(ctx)
	}
	var value app.PetOverlayState
	err := call(ctx, s.Client, "PetSettingsService", "GetPetPresentation", []any{}, &value)
	return value, err
}

func (s *PetSettingsService) RefreshPetCatalog(ctx context.Context) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.RefreshPetCatalog(ctx)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "RefreshPetCatalog", []any{}, &value)
	return value, err
}

func (s *PetSettingsService) PreviewPet(ctx context.Context, stableSourceKey string) (app.PetPreview, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPreview{}, err
		}
		return s.Local.PreviewPet(ctx, stableSourceKey)
	}
	var value app.PetPreview
	err := call(ctx, s.Client, "PetSettingsService", "PreviewPet", []any{stableSourceKey}, &value)
	return value, err
}

func (s *PetSettingsService) GetPetPreview(ctx context.Context, previewRef string) (string, error) {
	if s.Local != nil {
		return s.Local.GetPetPreview(ctx, previewRef)
	}
	var value string
	err := call(ctx, s.Client, "PetSettingsService", "GetPetPreview", []any{previewRef}, &value)
	return value, err
}

func (s *PetSettingsService) SelectPet(ctx context.Context, stableSourceKey string) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.SelectPet(ctx, stableSourceKey)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "SelectPet", []any{stableSourceKey}, &value)
	return value, err
}

func (s *PetSettingsService) SetPetAlwaysOnTop(ctx context.Context, enabled bool) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.SetPetAlwaysOnTop(ctx, enabled)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "SetPetAlwaysOnTop", []any{enabled}, &value)
	return value, err
}

func (s *PetSettingsService) SetPetVisibility(ctx context.Context, visible bool) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.SetPetVisibility(ctx, visible)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "SetPetVisibility", []any{visible}, &value)
	return value, err
}

func (s *PetSettingsService) SetPetSize(ctx context.Context, percent int) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.SetPetSize(ctx, percent)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "SetPetSize", []any{percent}, &value)
	return value, err
}

func (s *PetSettingsService) ClearPetSelection(ctx context.Context) (app.PetPanel, error) {
	if s.Local != nil {
		if err := s.localMaintenanceFailure(); err != nil {
			return app.PetPanel{}, err
		}
		return s.Local.ClearPetSelection(ctx)
	}
	var value app.PetPanel
	err := call(ctx, s.Client, "PetSettingsService", "ClearPetSelection", []any{}, &value)
	return value, err
}
