// Code generated by scripts/generate-daemon-client.py; DO NOT EDIT.
package desktopclient

import (
	"context"
	"github.com/local/dsh-work/internal/app"
	"github.com/local/dsh-work/internal/daemon"
	"github.com/local/dsh-work/internal/settings"
)

type SettingsService struct {
	Client *daemon.Client
	Local  *app.SettingsService
}

func (s *SettingsService) SetAutomaticRuntimeRollback(ctx context.Context, enabled bool) (settings.Values, error) {
	if s.Local != nil {
		return s.Local.SetAutomaticRuntimeRollback(ctx, enabled)
	}
	var value settings.Values
	err := call(ctx, s.Client, "SettingsService", "SetAutomaticRuntimeRollback", []any{enabled}, &value)
	return value, err
}

func (s *SettingsService) GetSettings(ctx context.Context) (settings.Values, error) {
	if s.Local != nil {
		return s.Local.GetSettings(ctx)
	}
	var value settings.Values
	err := call(ctx, s.Client, "SettingsService", "GetSettings", []any{}, &value)
	return value, err
}

func (s *SettingsService) SetLocale(ctx context.Context, locale string) (settings.Values, error) {
	if s.Local != nil {
		return s.Local.SetLocale(ctx, locale)
	}
	var value settings.Values
	err := call(ctx, s.Client, "SettingsService", "SetLocale", []any{locale}, &value)
	return value, err
}

func (s *SettingsService) SetNotificationPreference(ctx context.Context, key string, enabled bool) (settings.Values, error) {
	if s.Local != nil {
		return s.Local.SetNotificationPreference(ctx, key, enabled)
	}
	var value settings.Values
	err := call(ctx, s.Client, "SettingsService", "SetNotificationPreference", []any{key, enabled}, &value)
	return value, err
}
