"""Generate typed native-client adapters from the existing service contracts."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
sources = [p.read_text(encoding="utf-8") for p in (root / "internal/app").glob("*.go") if not p.name.endswith("_test.go")]
types = set(re.findall(r"^type (\w+) ", "\n".join(sources), re.M))
services = ["HostService", "ManagerService", "SettingsService", "StorageService", "PetSettingsService"]
imports = {"context": "context", "app": "github.com/local/dsh-work/internal/app", "daemon": "github.com/local/dsh-work/internal/daemon"}
for source in sources:
    for path in re.findall(r'"(github.com/local/dsh-work/internal/[^"\n]+)"', source):
        imports[path.rsplit("/", 1)[-1]] = path

def qualify(text):
    return re.sub(r"(?<![\w.])\b(" + "|".join(sorted(types, key=len, reverse=True)) + r")\b", r"app.\1", text)

for service in services:
    methods = []
    for source in sources:
        for m in re.finditer(r"func \(s \*" + service + r"\) ([A-Z]\w*)\((ctx context.Context[^)]*)\) ([^{\n]+) \{", source):
            name, params, result = m.groups()
            args = []
            for param in params.split(",")[1:]:
                args.append(param.strip().split()[0])
            results = [part.strip().split()[-1] for part in result.strip("()").split(",")]
            output = results[0] if results[0] != "error" else None
            has_error = results[-1] == "error"
            body = "\tif s.Local != nil { return s.Local." + name + "(ctx" + (", " + ", ".join(args) if args else "") + ") }\n"
            if output:
                body += "\tvar value " + qualify(output) + "\n"
            body += '\terr := call(ctx, s.Client, "' + service + '", "' + name + '", []any{' + ", ".join(args) + "}, " + ("&value" if output else "nil") + ")\n"
            if not has_error:
                body += "\tif err != nil { panic(err) }\n\treturn value\n"
            else:
                body += "\treturn " + ("value, " if output else "") + "err\n"
            methods.append("func (s *" + service + ") " + name + "(" + qualify(params) + ") " + qualify(result) + " {\n" + body + "}\n")
    body = "type " + service + " struct { Client *daemon.Client; Local *app." + service + " }\n\n" + "\n".join(methods)
    used = {key: value for key, value in imports.items() if re.search(r"\b" + key + r"\.", body)}
    text = "// Code generated by scripts/generate-daemon-client.py; DO NOT EDIT.\npackage desktopclient\n\nimport (\n" + "".join('\t"' + path + '"\n' for path in used.values()) + ")\n\n" + body
    (root / "internal/desktopclient" / (service.lower() + ".go")).write_text(text, encoding="utf-8")
