// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Availability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AvailabilityReady = "ready",
    AvailabilityInvalid = "invalid",
};

export enum BaseState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BaseStarting = "starting",
    BaseIdle = "idle",
    BaseWorking = "working",
    BaseThinking = "thinking",
    BaseResult = "result",
    BaseWaiting = "waiting",
    BaseReviewing = "reviewing",
    BaseCompleted = "completed",
    BaseFailed = "failed",
    BaseOffline = "offline",
};

/**
 * CatalogRoot is safe to expose to a caller. It intentionally contains no
 * resolved or absolute filesystem path.
 */
export interface CatalogRoot {
    "kind": RootKind;
    "status": RootStatus;
}

/**
 * CatalogSnapshot is an immutable read model. Snapshot() and every operation
 * returning one create fresh slices, maps, and timestamps for the caller.
 */
export interface CatalogSnapshot {
    "revision": number;
    "scanState": ScanState;
    "stale": boolean;
    "scannedAt"?: string | null;
    "roots"?: CatalogRoot[] | null;
    "items"?: PetListItem[] | null;
    "issues"?: Issue[] | null;
}

export enum EffectiveVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VisibilityVisible = "visible",
    VisibilityHidden = "hidden",
    VisibilityPaused = "paused",
};

export interface FrameRef {
    "index": number;
    "durationMs": number;
    "assetId"?: string;
    "x"?: number;
    "y"?: number;
    "width"?: number;
    "height"?: number;
}

/**
 * Issue is a bounded, safe diagnostic. Args may contain only safe, truncated
 * values such as a folder identity or resource kind.
 */
export interface Issue {
    "code": string;
    "args"?: { [_ in string]?: string } | null;
    "sourceKind": SourceKind;
    "retryable": boolean;
    "severity": IssueSeverity;
    "safeFallbackSummary"?: string;
}

export enum IssueSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityInfo = "info",
    SeverityWarning = "warning",
    SeverityError = "error",
};

export interface LookSnapshot {
    "mode": string;
    "angle": number;
    "direction": number;
    "normalizedX": number;
    "normalizedY": number;
}

export enum OverlayStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OverlayStopped = "stopped",
    OverlayHidden = "hidden",
    OverlayVisible = "visible",
    OverlayPreparing = "preparing",
    OverlayFailed = "failed",
};

/**
 * PetListItem is a safe selectable summary. A catalog never exposes the
 * package root, manifest path, or raw resource URL here.
 */
export interface PetListItem {
    "stableSourceKey": string;
    "displayName": string;
    "description"?: string;
    "sourceBadge": SourceBadge;
    "availability": Availability;
    "current": boolean;
    "previewRef"?: string;
    "capabilities"?: string[] | null;
    "issueCodes"?: string[] | null;
}

/**
 * PetRuntimeSnapshot is a read-only projection consumed by a renderer or the
 * overlay. It contains no source-format row/column knowledge.
 */
export interface PetRuntimeSnapshot {
    "elapsedMs": number;
    "loop": boolean;
    "repeatCount": number;
    "playbackId": number;
    "baseState": BaseState;
    "action"?: string;
    "baseTrackId"?: string;
    "baseFrameIndex"?: number;
    "actionTrackId"?: string;
    "actionFrameIndex"?: number;
    "lookTrackId"?: string;
    "lookFrameIndex": number;
    "look": LookSnapshot;
    "progress": number;
    "trackId": string;
    "frameIndex": number;
    "effectiveVisibility"?: EffectiveVisibility;
    "overlayStatus"?: OverlayStatus;
    "selectionStatus"?: SelectionStatus;
    "reducedMotion": boolean;
    "diagnostics"?: Issue[] | null;
    "at": number;
}

/**
 * Playback contains only validated media coordinates and opaque Host URLs.
 * Resource paths and source package metadata never cross this boundary.
 */
export interface Playback {
    "video": boolean;
    "key": string;
    "assets": { [_ in string]?: string } | null;
    "tracks": { [_ in string]?: FrameRef[] | null } | null;
    "look": { [_ in `${number}`]?: FrameRef } | null;
}

/**
 * RootKind and RootStatus are the safe root projections exposed by a catalog
 * snapshot.
 */
export enum RootKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RootCodexPets = "codex-pets",
    RootCodexAvatars = "codex-avatars",
};

export enum RootStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RootAvailable = "available",
    RootMissing = "missing",
    RootUnreadable = "unreadable",
};

/**
 * RuntimeState is the small service-level projection required by Settings.
 * Rendering details remain in PetRuntimeSnapshot.
 */
export interface RuntimeState {
    "selectedKey": string | null;
    "persistedVisibilityIntent": string;
    "effectiveVisibility": EffectiveVisibility;
    "selectionStatus": SelectionStatus;
    "overlayStatus": OverlayStatus;
    "failureCode"?: string;
}

/**
 * ScanState describes the publication state of a catalog snapshot.
 */
export enum ScanState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScanNeverScanned = "never-scanned",
    ScanScanning = "scanning",
    ScanReady = "ready",
    ScanFailed = "failed",
};

export enum SelectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SelectionNone = "none",
    SelectionReady = "ready",
    SelectionUnavailable = "unavailable",
    SelectionInvalid = "invalid",
    SelectionSwitching = "switching",
};

export enum SourceBadge {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BadgeCodex = "codex",
    BadgeDshNative = "dsh-native",
};

/**
 * SourceKind is a safe source label. It is not a filesystem path.
 */
export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceCodexPets = "codex-pets",

    /**
     * SourceCodexAvatars is the Codex compatibility root. It uses the same
     * Codex manifest and atlas contract as SourceCodexPets.
     */
    SourceCodexAvatars = "codex-avatars",
    SourceCommunity = "dsh-community",
    SourceDshPets = "dsh-pets",
    SourceCodexHome = "codex-home",
    SourceUnknown = "unknown",
};
