// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Preferences is persisted by dsh-work and projected to the trusted Settings
 * surface. Defaults keep meaningful task and error signals available while
 * leaving routine lifecycle noise off.
 */
export interface Preferences {
    "enabled": boolean;
    "completed": boolean;
    "interactionRequired": boolean;
    "errors": boolean;
    "lifecycle": boolean;
}
